// Cloudflare Worker bindings interface
// The Env interface is auto-generated by `wrangler types` in worker-configuration.d.ts
// This file provides additional type declarations

declare module "react-router" {
	export interface AppLoadContext {
		cloudflare: {
			env: Env;
			ctx: ExecutionContext;
		};
	}
}
