import type { FieldOption } from "../../types/form-config";

export const THAI_PROVINCES: FieldOption[] = [
	{ value: "กระบี่", label: { th: "กระบี่", en: "Krabi" } },
	{ value: "กรุงเทพมหานคร", label: { th: "กรุงเทพมหานคร", en: "Bangkok" } },
	{ value: "กาญจนบุรี", label: { th: "กาญจนบุรี", en: "Kanchanaburi" } },
	{ value: "กาฬสินธุ์", label: { th: "กาฬสินธุ์", en: "Kalasin" } },
	{ value: "กำแพงเพชร", label: { th: "กำแพงเพชร", en: "Kamphaeng Phet" } },
	{ value: "ขอนแก่น", label: { th: "ขอนแก่น", en: "Khon Kaen" } },
	{ value: "จันทบุรี", label: { th: "จันทบุรี", en: "Chanthaburi" } },
	{ value: "ฉะเชิงเทรา", label: { th: "ฉะเชิงเทรา", en: "Chachoengsao" } },
	{ value: "ชลบุรี", label: { th: "ชลบุรี", en: "Chonburi" } },
	{ value: "ชัยนาท", label: { th: "ชัยนาท", en: "Chai Nat" } },
	{ value: "ชัยภูมิ", label: { th: "ชัยภูมิ", en: "Chaiyaphum" } },
	{ value: "ชุมพร", label: { th: "ชุมพร", en: "Chumphon" } },
	{ value: "เชียงราย", label: { th: "เชียงราย", en: "Chiang Rai" } },
	{ value: "เชียงใหม่", label: { th: "เชียงใหม่", en: "Chiang Mai" } },
	{ value: "ตรัง", label: { th: "ตรัง", en: "Trang" } },
	{ value: "ตราด", label: { th: "ตราด", en: "Trat" } },
	{ value: "ตาก", label: { th: "ตาก", en: "Tak" } },
	{ value: "นครนายก", label: { th: "นครนายก", en: "Nakhon Nayok" } },
	{ value: "นครปฐม", label: { th: "นครปฐม", en: "Nakhon Pathom" } },
	{ value: "นครพนม", label: { th: "นครพนม", en: "Nakhon Phanom" } },
	{ value: "นครราชสีมา", label: { th: "นครราชสีมา", en: "Nakhon Ratchasima" } },
	{ value: "นครศรีธรรมราช", label: { th: "นครศรีธรรมราช", en: "Nakhon Si Thammarat" } },
	{ value: "นครสวรรค์", label: { th: "นครสวรรค์", en: "Nakhon Sawan" } },
	{ value: "นนทบุรี", label: { th: "นนทบุรี", en: "Nonthaburi" } },
	{ value: "นราธิวาส", label: { th: "นราธิวาส", en: "Narathiwat" } },
	{ value: "น่าน", label: { th: "น่าน", en: "Nan" } },
	{ value: "บึงกาฬ", label: { th: "บึงกาฬ", en: "Bueng Kan" } },
	{ value: "บุรีรัมย์", label: { th: "บุรีรัมย์", en: "Buriram" } },
	{ value: "ปทุมธานี", label: { th: "ปทุมธานี", en: "Pathum Thani" } },
	{ value: "ประจวบคีรีขันธ์", label: { th: "ประจวบคีรีขันธ์", en: "Prachuap Khiri Khan" } },
	{ value: "ปราจีนบุรี", label: { th: "ปราจีนบุรี", en: "Prachin Buri" } },
	{ value: "ปัตตานี", label: { th: "ปัตตานี", en: "Pattani" } },
	{ value: "พระนครศรีอยุธยา", label: { th: "พระนครศรีอยุธยา", en: "Phra Nakhon Si Ayutthaya" } },
	{ value: "พะเยา", label: { th: "พะเยา", en: "Phayao" } },
	{ value: "พังงา", label: { th: "พังงา", en: "Phang Nga" } },
	{ value: "พัทลุง", label: { th: "พัทลุง", en: "Phatthalung" } },
	{ value: "พิจิตร", label: { th: "พิจิตร", en: "Phichit" } },
	{ value: "พิษณุโลก", label: { th: "พิษณุโลก", en: "Phitsanulok" } },
	{ value: "เพชรบุรี", label: { th: "เพชรบุรี", en: "Phetchaburi" } },
	{ value: "เพชรบูรณ์", label: { th: "เพชรบูรณ์", en: "Phetchabun" } },
	{ value: "แพร่", label: { th: "แพร่", en: "Phrae" } },
	{ value: "ภูเก็ต", label: { th: "ภูเก็ต", en: "Phuket" } },
	{ value: "มหาสารคาม", label: { th: "มหาสารคาม", en: "Maha Sarakham" } },
	{ value: "มุกดาหาร", label: { th: "มุกดาหาร", en: "Mukdahan" } },
	{ value: "แม่ฮ่องสอน", label: { th: "แม่ฮ่องสอน", en: "Mae Hong Son" } },
	{ value: "ยโสธร", label: { th: "ยโสธร", en: "Yasothon" } },
	{ value: "ยะลา", label: { th: "ยะลา", en: "Yala" } },
	{ value: "ร้อยเอ็ด", label: { th: "ร้อยเอ็ด", en: "Roi Et" } },
	{ value: "ระนอง", label: { th: "ระนอง", en: "Ranong" } },
	{ value: "ระยอง", label: { th: "ระยอง", en: "Rayong" } },
	{ value: "ราชบุรี", label: { th: "ราชบุรี", en: "Ratchaburi" } },
	{ value: "ลพบุรี", label: { th: "ลพบุรี", en: "Lop Buri" } },
	{ value: "ลำปาง", label: { th: "ลำปาง", en: "Lampang" } },
	{ value: "ลำพูน", label: { th: "ลำพูน", en: "Lamphun" } },
	{ value: "เลย", label: { th: "เลย", en: "Loei" } },
	{ value: "ศรีสะเกษ", label: { th: "ศรีสะเกษ", en: "Si Sa Ket" } },
	{ value: "สกลนคร", label: { th: "สกลนคร", en: "Sakon Nakhon" } },
	{ value: "สงขลา", label: { th: "สงขลา", en: "Songkhla" } },
	{ value: "สตูล", label: { th: "สตูล", en: "Satun" } },
	{ value: "สมุทรปราการ", label: { th: "สมุทรปราการ", en: "Samut Prakan" } },
	{ value: "สมุทรสงคราม", label: { th: "สมุทรสงคราม", en: "Samut Songkhram" } },
	{ value: "สมุทรสาคร", label: { th: "สมุทรสาคร", en: "Samut Sakhon" } },
	{ value: "สระแก้ว", label: { th: "สระแก้ว", en: "Sa Kaeo" } },
	{ value: "สระบุรี", label: { th: "สระบุรี", en: "Saraburi" } },
	{ value: "สิงห์บุรี", label: { th: "สิงห์บุรี", en: "Sing Buri" } },
	{ value: "สุโขทัย", label: { th: "สุโขทัย", en: "Sukhothai" } },
	{ value: "สุพรรณบุรี", label: { th: "สุพรรณบุรี", en: "Suphan Buri" } },
	{ value: "สุราษฎร์ธานี", label: { th: "สุราษฎร์ธานี", en: "Surat Thani" } },
	{ value: "สุรินทร์", label: { th: "สุรินทร์", en: "Surin" } },
	{ value: "หนองคาย", label: { th: "หนองคาย", en: "Nong Khai" } },
	{ value: "หนองบัวลำภู", label: { th: "หนองบัวลำภู", en: "Nong Bua Lam Phu" } },
	{ value: "อ่างทอง", label: { th: "อ่างทอง", en: "Ang Thong" } },
	{ value: "อำนาจเจริญ", label: { th: "อำนาจเจริญ", en: "Amnat Charoen" } },
	{ value: "อุดรธานี", label: { th: "อุดรธานี", en: "Udon Thani" } },
	{ value: "อุตรดิตถ์", label: { th: "อุตรดิตถ์", en: "Uttaradit" } },
	{ value: "อุทัยธานี", label: { th: "อุทัยธานี", en: "Uthai Thani" } },
	{ value: "อุบลราชธานี", label: { th: "อุบลราชธานี", en: "Ubon Ratchathani" } },
];
